compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  react-dom@*:
    dependencies:
      "@types/react-dom": 19.0.2
  react@*:
    dependencies:
      "@types/react": 19.0.1

yarnPath: .yarn/releases/yarn-4.6.0.cjs
