compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.3.1.cjs

packageExtensions:
  "react-responsive-masonry@*":
    peerDependencies:
      "prop-types": "*"

  "@storybook/nextjs@*":
    peerDependencies:
      sass: "*"
      sass-loader: "*"
