import clsx from 'clsx';

import { pretendardFont, senFont } from './fonts';

import 'src/styles/global.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" className={clsx(senFont.variable, pretendardFont.variable)}>
      <body>{children}</body>
    </html>
  );
}

export default RootLayout;
